DSPs prepared for loading persisted models
sdatkinson/NeuralAmpModelerCore pull request #35
Opened 2023-04-18 08:29 UTC by pawelKapl

Few changes that will enable loading models from serialized sources:

- added IR snapshot - a small struct that will allow to capture current IR configuration, and then recover IR basing on it
- removed loading file responsibility from DSP - now it will accept ready json. 

This is a part of the solution for issue #163

Not fully tested yet, opened for all the suggestions!

2023-04-21 09:39 UTC, pawelKapl commented
Hey @sdatkinson did u have a time to take a look at this one? It is now polished, tested well 🤞 , and introduces much less 'breaking changes'. Thanks!

2023-04-21 14:44 UTC, sdatkinson commented
Thanks! I'll hopefully have time to look this weekend

2023-05-27 22:16 UTC, sdatkinson requested changes
Thanks for your patience, getting back to this.

Could you have a look at the changes merged in #46 and see if that resolves your changes in `dsp.h` and `get_dsp.cpp`? I think those changes can be dropped. (This is the part I'm requesting be changed before I can approve

IR part looks good except naming nits; your call whether to grab.

Thanks!

2023-05-27 22:16 UTC, sdatkinson commented on dsp/ImpulseResponse.h
> +struct dsp::ImpulseResponse::IRSnapshot
Nit: name `IRData`?

2023-05-27 22:16 UTC, sdatkinson commented on dsp/ImpulseResponse.h
> +  IRSnapshot TakeIRSnapshot();
Nit: name `GetData`?

2023-06-02 17:54 UTC, pawelKapl commented
@sdatkinson Yeah i think i can marry it without my changes. Dropped them, and changed naming. Now should be fine!

2023-06-11 04:46 UTC, sdatkinson requested changes
Just the one and we're good. Thanks!

2023-06-11 04:46 UTC, sdatkinson commented on dsp/ImpulseResponse.h
> +  struct IRData;
Can we get this removed? Doesn't seem to be doing anything except hanging out on the public interface?

2023-06-11 13:10 UTC, pawelKapl commented on dsp/ImpulseResponse.h
> +  struct IRData;
Hey @sdatkinson I declared it there cause this struct is a part of public API - public recovery constructor. Needs to be declared above constructor to allow compilation.

2023-06-23 01:46 UTC, sdatkinson approved these changes
LGTM! 👍🏻

2023-06-23 01:46 UTC, merged